name: 'Test project'

description: 'Run project unittests'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: dotnet restore
      shell: bash
    - name: Build
      run: dotnet build --configuration Release --no-restore
      shell: bash
    - name: Run tests
      run: dotnet test --configuration Release --verbosity m --no-restore
      shell: bash
