check_changing:
  runs-on: ubuntu-latest
  
  steps:
  - name: Check out repository code
    uses: actions/checkout@v3
  - name: Check does code or test changed
    uses: dorny/paths-filter@v2
    id: changed_obj
    with:
      # inline YAML or path to separate file (e.g.: .github/filters.yaml)
      filters: |
        code:
          - ${{ env.code_path }}
        test:
          - ${{ env.test_path }}
  
  outputs:
    code_changed: ${{ steps.changed_obj.outputs.code }}  
    test_changed: ${{ steps.changed_obj.outputs.test }}  